version: '3.8'

services:
  paper-alchemist:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull llava && 
             wait"

volumes:
  ollama_data: